language: node_js
node_js:
  - "10"
services:
  - docker
before_install:
  - sudo service postgresql stop
  - sudo docker-compose up -d db
before_script:
  - sequelize db:migrate || true
branches:
  only:
    - master
