version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - ./:/opt/api/
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: internet_movie_database_api
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
