version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env.prod
    depends_on:
      - db
    volumes:
      - ./:/opt/api/
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
